steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--build-args", "NPM_TOKEN=${_NPM_TOKEN}", "-t", "gcr.io/chingu/accounts-service:$REVISION_ID", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/chingu/accounts-service:$REVISION_ID"]
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["set", "image", "deployment/accounts-service", "app=gcr.io/chingu/accounts-service:$REVISION_ID"]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
images:
  - "gcr.io/chingu/accounts-service:$REVISION_ID"