apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  labels:
    app: accounts-service
spec:
  type: ClusterIP
  selector:
    app: accounts-service
  ports:
    - port: 80
      targetPort: http-server
